# Generated by Django 2.1.2 on 2018-11-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20181120_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='actual_amount_spent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='estimated_total_budget',
            field=models.IntegerField(),
        ),
    ]
