# Generated by Django 2.1.2 on 2018-12-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20181205_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='logged_in_user',
        ),
    ]
