# Generated by Django 2.1.2 on 2018-11-21 03:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181120_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('description', models.CharField(max_length=200)),
                ('related_vendor', models.CharField(choices=[(pages.models.VendorTypes('Photographer'), 'Photographer'), (pages.models.VendorTypes('Videographer'), 'Videographer'), (pages.models.VendorTypes('Decorator'), 'Decorator'), (pages.models.VendorTypes('Caterer'), 'Caterer'), (pages.models.VendorTypes('Bartender'), 'Bartender')], max_length=5)),
                ('location', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timelinetask',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Event'),
        ),
    ]
