# Generated by Django 2.1.2 on 2018-11-21 03:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20181120_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklisTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('assignee', models.CharField(max_length=200)),
                ('client_note', models.CharField(max_length=200)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('wedding', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Wedding')),
            ],
        ),
    ]
