# Generated by Django 2.1.2 on 2018-11-21 03:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_checklistask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_total_budget', models.IntegerField(max_length=200)),
                ('actual_amount_spent', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.IntegerField(max_length=200)),
                ('contracted_price', models.IntegerField(max_length=200)),
                ('payment_price', models.IntegerField(max_length=200)),
                ('vendor_type', models.CharField(choices=[(pages.models.VendorTypes('Photographer'), 'Photographer'), (pages.models.VendorTypes('Videographer'), 'Videographer'), (pages.models.VendorTypes('Decorator'), 'Decorator'), (pages.models.VendorTypes('Caterer'), 'Caterer'), (pages.models.VendorTypes('Bartender'), 'Bartender')], max_length=5)),
                ('client_note', models.CharField(max_length=200)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('payee', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
                ('budget', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Budget')),
            ],
        ),
        migrations.AddField(
            model_name='wedding',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Budget'),
        ),
    ]
