# Generated by Django 2.1.2 on 2018-12-06 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20181202_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='primary_user',
            new_name='client_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='wedding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Wedding'),
        ),
    ]
